// words.js
const vocabData = [
  { word: "access", partOfSpeech: "noun/verb", definition: "The ability, right, or permission to approach, enter, or use something." },
  { word: "accurate", partOfSpeech: "adjective", definition: "Correct, precise, and free from errors." },
  { word: "achieve", partOfSpeech: "verb", definition: "To successfully bring about or reach a desired objective by effort or skill." },
  { word: "acquire", partOfSpeech: "verb", definition: "To gain asset, object, or reliable knowledge for oneself." },
  { word: "adequate", partOfSpeech: "adjective", definition: "Satisfactory or acceptable in quality or quantity for a particular need." },
  { word: "adjust", partOfSpeech: "verb", definition: "To alter slightly to achieve a better fit, match, or functional state." },
  { word: "administration", partOfSpeech: "noun", definition: "The management or systematic organizing of business, operations, or institutions." },
  { word: "affect", partOfSpeech: "verb", definition: "To make a difference to, influence, or produce a physical or emotional change in." },
  { word: "alter", partOfSpeech: "verb", definition: "To change or modify structurally or characteristically without replacing entirely." },
  { word: "alternative", partOfSpeech: "noun/adjective", definition: "One of two or more available possibilities or distinct choices." },
  { word: "analyze", partOfSpeech: "verb", definition: "To examine something methodically and in detail to explain its nature or structure." },
  { word: "annual", partOfSpeech: "adjective", definition: "Occurring once every year; calculated over the period of one calendar year." },
  { word: "apparent", partOfSpeech: "adjective", definition: "Clearly visible, obvious, or understood; seeming real but not necessarily true." },
  { word: "approach", partOfSpeech: "verb/noun", definition: "A way of dealing with a situation or problem; drawing physically or conceptually closer." },
  { word: "area", partOfSpeech: "noun", definition: "A region or part of a town, country, body, or specific field of study." },
  { word: "aspect", partOfSpeech: "noun", definition: "A particular part, feature, or distinct angle of a multifaceted matter." },
  { word: "assess", partOfSpeech: "verb", definition: "To evaluate or estimate the nature, ability, value, or quality of something." },
  { word: "assist", partOfSpeech: "verb", definition: "To help someone by sharing work, providing resources, or adding support." },
  { word: "assume", partOfSpeech: "verb", definition: "To suppose that something is true without verified proof or absolute evidence." },
  { word: "attitude", partOfSpeech: "noun", definition: "A settled way of thinking or feeling, typically reflected in a person's behavior." },
  { word: "attribute", partOfSpeech: "verb/noun", definition: "To regard something as being caused by a specific factor; a characteristic quality." },
  { word: "authority", partOfSpeech: "noun", definition: "The power, official right, or institutional capacity to give orders and enforce compliance." },
  { word: "available", partOfSpeech: "adjective", definition: "Able to be used, obtained, or reached easily at this moment." },
  { word: "aware", partOfSpeech: "adjective", definition: "Having knowledge or perception of a situation, fact, or sensory development." },
  { word: "benefit", partOfSpeech: "noun/verb", definition: "An advantage, profit, or positive gain derived from an action or resource." },
  { word: "brief", partOfSpeech: "adjective", definition: "Of short duration; concise and using few words to convey core details." },
  { word: "capable", partOfSpeech: "adjective", definition: "Having the ability, fitness, power, or necessary skills to achieve something." },
  { word: "capacity", partOfSpeech: "noun", definition: "The maximum amount that something can contain; total functional capability." },
  { word: "challenge", partOfSpeech: "noun/verb", definition: "A task or situation that tests someone's abilities; a call to prove something." },
  { word: "circumstance", partOfSpeech: "noun", definition: "A fact or condition connected with or relevant to an event or action." },
  { word: "comment", partOfSpeech: "noun/verb", definition: "A verbal or written remark expressing an opinion, reaction, or explanation." },
  { word: "commit", partOfSpeech: "verb", definition: "To dedicate resources, energy, or oneself to a specific course of action." },
  { word: "community", partOfSpeech: "noun", definition: "A group of people living in the same place or sharing a common characteristic." },
  { word: "compensate", partOfSpeech: "verb", definition: "To give someone something (typically money) in recognition of loss or work." },
  { word: "complex", partOfSpeech: "adjective", definition: "Consisting of many different and connected parts; intricate or complicated." },
  { word: "component", partOfSpeech: "noun", definition: "A constituent part or element of a larger machine, system, or concept." },
  { word: "concentrate", partOfSpeech: "verb", definition: "To focus one's full attention or mental effort intensely on a single object." },
  { word: "concept", partOfSpeech: "noun", definition: "An abstract idea, structural layout, or general mental notion." },
  { word: "conduct", partOfSpeech: "verb/noun", definition: "To organize and carry out an activity; a person's visible behavior." },
  { word: "conflict", partOfSpeech: "noun/verb", definition: "A serious disagreement, argument, or clash between opposing ideas." },
  { word: "consequence", partOfSpeech: "noun", definition: "A result, effect, or outcome of an action or condition, often unwelcome." },
  { word: "considerable", partOfSpeech: "adjective", definition: "Notably large in size, amount, extent, or cultural importance." },
  { word: "consist", partOfSpeech: "verb", definition: "To be composed or made up of specific items or operational variables." },
  { word: "constant", partOfSpeech: "adjective", definition: "Occurring continuously over a period of time; remaining unchanging." },
  { word: "constitute", partOfSpeech: "verb", definition: "To be a part of a whole; to combine to establish or form a law or system." },
  { word: "constrain", partOfSpeech: "verb", definition: "To severely restrict the scope, activity, or operational freedom of." },
  { word: "construct", partOfSpeech: "verb", definition: "To build, assemble, or systematically formulate an object or complex theory." },
  { word: "consume", partOfSpeech: "verb", definition: "To eat, drink, ingest, or completely use up resources like time or fuel." },
  { word: "contact", partOfSpeech: "noun/verb", definition: "State of physical touching, meeting, or communicating with an outside party." },
  { word: "context", partOfSpeech: "noun", definition: "The circumstances that form the setting for an event, statement, or idea." },
  { word: "contrast", partOfSpeech: "noun/verb", definition: "The state of being strikingly different from something else when juxtaposed." },
  { word: "contribute", partOfSpeech: "verb", definition: "To give or supply money, assets, or effort toward a common fund or goal." },
  { word: "coordinate", partOfSpeech: "verb", definition: "To bring the different elements of a complex activity into an efficient relationship." },
  { word: "core", partOfSpeech: "noun/adjective", definition: "The central, foundational, or most vital part of something." },
  { word: "correspond", partOfSpeech: "verb", definition: "To have a close similarity, match, or regularly exchange letters/data." },
  { word: "criteria", partOfSpeech: "noun (plural)", definition: "Principles, standards, or tests by which something may be judged or decided." },
  { word: "culture", partOfSpeech: "noun", definition: "The ideas, customs, and social behavior of a particular people or society." },
  { word: "data", partOfSpeech: "noun", definition: "Facts and statistics collected together for reference, storage, or analysis." },
  { word: "debate", partOfSpeech: "noun/verb", definition: "A formal discussion on a particular topic in a public meeting or structure." },
  { word: "decline", partOfSpeech: "verb/noun", definition: "To become smaller, fewer, or less; a polite refusal to accept an offer." },
  { word: "deduce", partOfSpeech: "verb", definition: "To arrive at a logical fact or conclusion by reasoning from known premises." },
  { word: "demonstrate", partOfSpeech: "verb", definition: "To clearly show, explain, or prove the existence or truth of something by evidence." },
  { word: "derive", partOfSpeech: "verb", definition: "To obtain, trace, or extract something from a specified origin or baseline source." },
  { word: "despite", partOfSpeech: "preposition", definition: "Without being affected by, stopped by, or altered by something mentioned." },
  { word: "discrete", partOfSpeech: "adjective", definition: "Individually separate, distinct, and completely disconnected from others." },
  { word: "distinct", partOfSpeech: "adjective", definition: "Recognizably different in nature from something else; physically clear." },
  { word: "distribute", partOfSpeech: "verb", definition: "To hand out, share, or spread a commodity or data across an area or group." },
  { word: "diverse", partOfSpeech: "adjective", definition: "Showing a great deal of variety; very different or multifaceted." },
  { word: "element", partOfSpeech: "noun", definition: "A part or aspect of something abstract, especially one that is essential." },
  { word: "emerge", partOfSpeech: "verb", definition: "To move out of or away from something and become visible or prominent." },
  { word: "emphasize", partOfSpeech: "verb", definition: "To give special importance, validation, or structural prominence to something." },
  { word: "enable", partOfSpeech: "verb", definition: "To give someone the authority, tools, or practical means to achieve a task." },
  { word: "enforce", partOfSpeech: "verb", definition: "To compel compliance with a law, institutional rule, or specific obligation." },
  { word: "entity", partOfSpeech: "noun", definition: "A thing with a distinct, independent, and legally valid existence." },
  { word: "equivalent", partOfSpeech: "adjective/noun", definition: "Equal in value, amount, function, meaning, or structural weight." },
  { word: "establish", partOfSpeech: "verb", definition: "To set up an organization, system, or set of rules on a firm, permanent basis." },
  { word: "estimate", partOfSpeech: "noun/verb", definition: "A roughly calculated, educated guess of the value, size, or cost of an item." },
  { word: "evaluate", partOfSpeech: "verb", definition: "To form an idea or assess the structural numeric value or merit of something." },
  { word: "evident", partOfSpeech: "adjective", definition: "Plainly obvious; clearly understood and backed by sensory observation." },
  { word: "exclude", partOfSpeech: "verb", definition: "To deny access, remove from a group, or bar from consideration intentionally." },
  { word: "expand", partOfSpeech: "verb", definition: "To become larger in size, scope, volume, or structural surface area." },
  { word: "expose", partOfSpeech: "verb", definition: "To make something visible by uncovering it; leaving unprotected from variables." },
  { word: "external", partOfSpeech: "adjective", definition: "Belonging to or forming the outer surface, structure, or outside of an item." },
  { word: "facilitate", partOfSpeech: "verb", definition: "To make an action, system, or dynamic sequence easier or less problematic." },
  { word: "factor", partOfSpeech: "noun", definition: "A circumstance, variable, or influence that contributes actively to an outcome." },
  { word: "feature", partOfSpeech: "noun/verb", definition: "A distinctive attribute, physical aspect, or characteristic of a product or entity." },
  { word: "focus", partOfSpeech: "noun/verb", definition: "The center of interest, clear optical concentration, or focal target point." },
  { word: "framework", partOfSpeech: "noun", definition: "An underlying essential supporting structure, ruleset, or system of ideas." },
  { word: "function", partOfSpeech: "noun/verb", definition: "An activity, job, or purpose natural to or intended for a person or thing." },
  { word: "fundamental", partOfSpeech: "adjective", definition: "Forming a necessary base, core framework, or central component of something." },
  { word: "furthermore", toughness: "adverb", definition: "In addition to what has already been stated; used to introduce a matching point." },
  { word: "generate", partOfSpeech: "verb", definition: "To produce, create, cause to arise, or bring into physical existence." },
  { word: "grant", partOfSpeech: "verb/noun", definition: "To agree to give, officially allow, or bestow an asset or legal privilege." },
  { word: "hence", partOfSpeech: "adverb", definition: "As a consequence; for this reason; pointing forward to a logical result." },
  { word: "hypothesis", partOfSpeech: "noun", definition: "A proposed, testable explanation made on the basis of limited starting evidence." },
  { word: "identify", partOfSpeech: "verb", definition: "To establish or indicate exactly who or what someone or something is." },
  { word: "illustrate", partOfSpeech: "verb", definition: "To explain or make something clear by using examples, charts, or images." },
  { word: "impact", partOfSpeech: "noun/verb", definition: "The striking of one object against another; a massive, highly visible effect." },
  { word: "imply", partOfSpeech: "verb", definition: "To strongly suggest the truth or existence of something without stating it directly." },
  { word: "indicate", partOfSpeech: "verb", definition: "To point out, show, or serve as a highly visible sign or direct signal of." },
  { word: "individual", partOfSpeech: "noun/adjective", definition: "Single; separate; characteristic of a single specific person or entity." },
  { word: "initial", partOfSpeech: "adjective", definition: "Existing or occurring at the absolute start or opening phase of a process." },
  { word: "instance", partOfSpeech: "noun", definition: "An example or single occurrence of something occurring or being true." },
  { word: "institute", partOfSpeech: "noun/verb", definition: "An organization having a particular purpose; to introduce a system or law." },
  { word: "integrate", partOfSpeech: "verb", definition: "To combine two or more things into a single, cohesive, functional whole." },
  { word: "internal", partOfSpeech: "adjective", definition: "Situated on the inside, domestic, or structural interior of an object." },
  { word: "interpret", partOfSpeech: "verb", definition: "To explain or translate the meaning of information, actions, or words cleanly." },
  { word: "invest", partOfSpeech: "verb", definition: "To allocate money, time, or energy to an asset with the expectation of a return." },
  { word: "investigate", partOfSpeech: "verb", definition: "To carry out a systematic, formal inquiry to discover hidden facts or truths." },
  { word: "involve", partOfSpeech: "verb", definition: "To include something as a necessary component, part, circumstance, or result." },
  { word: "issue", partOfSpeech: "noun/verb", definition: "An important topic or problem for debate; to distribute something officially." }
];
